package com.pragma.bootcamp_service.domain.exception;

public enum DomainErrorCode {
    VALIDATION_ERROR,
    INVALID_TOKEN,
    ACCESS_DENIED,
    DUPLICATE_NAME,
    CAPABILITY_NOT_FOUNT,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_ERROR,
    INVALID_PAGE,
    INVALID_SIZE,
    INVALID_SORT_BY,
    INVALID_DIRECTION,
    BOOTCAMP_NOT_FOUND,
    PARTICIPANT_ALREADY_ENROLLED,
    MAX_ACTIVE_BOOTCAMPS_REACHED,
    BOOTCAMP_SCHEDULE_CONFLICT

}
